### ISSUE TITLE
Runtime error when updating register values

### ISSUE THREAD

**Issue by chenchenpowin** [stepfunc/rodbus#133]
Hi @jadamcrain ,

I'm actively using your library and facing another issue. When I update the register values from server side by this code:
```
RuntimeConfig runtimeConfig = new RuntimeConfig().withNumCoreThreads(ushort(4));
Runtime runtime = new Runtime(runtimeConfig);

DeviceMap map = new DeviceMap();
map.addEndpoint(ubyte(1), new ExampleWriteHandler(), db -> {
    for(int i = 0; i < 1000; i++) {
        db.addHoldingRegister(ushort(i), ushort(1));
        db.addInputRegister(ushort(i), ushort(2));
    }
});
AddressFilter addressFilter = new AddressFilter("*.*.*.*");
Server server = Server.createTcp(runtime, "0.0.0.0", ushort(8888), addressFilter, ushort(100), map, DecodeLevel.nothing());
server.updateDatabase(ubyte(1), db -> {
    db.updateHoldingRegister(ushort(100), ushort(-1));
});
```
And the error is:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: JavaException', /target/aarch64-unknown-linux-gnu/release/build/rodbus-ffi-java-1095f2a2549debe7/out/jni.rs:3439:187
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 2216477728
```

I'm running on ubuntu VM, and cpu info:
```Architecture:           aarch64
  CPU op-mode(s):       64-bit
  Byte Order:           Little Endian
```

Please advise what can be done to get rid of this issue?

Thanks!

**Comment by chenchenpowin** [comment]
My bad. Cannot set negative value!

**Comment by jadamcrain** [comment]
@chenchenpowin 

Yes, that's the root cause.

`ushort(-1)` throws a Java exception, but it does so from a native thread.

When you run the following...

```
server.updateDatabase(ubyte(1), db -> {
    db.updateHoldingRegister(ushort(100), ushort(-1));
});
```

... the lambda expression is getting passed into a native (Rust) function and then is executed there.

If you can't guarantee that values aren't within the ranges for `ushort`, `uint`, etc you might consider creating the values **outside** of the database transaction and then capture those references inside the lambda.

I really dislike that Java doesn't have unsigned integers. It's a real pain when you have something like a protocol specification that defines things like unsigned 16-bit numbers. 😞
